### ISSUE TITLE
Doesn't build with GHC 9.2

### ISSUE THREAD

**Issue by expipiplus1** [ekmett/charset#15]
After word representation changes in ghc-prim

```
[1 of 9] Compiling Data.CharSet.ByteSet ( src/Data/CharSet/ByteSet.hs, dist/build/Data/CharSet/ByteSet.o, dist/build/Data/CharSet/ByteSet.dyn_o )

src/Data/CharSet/ByteSet.hs:53:32: error:
    • Couldn't match expected type ‘ghc-prim-0.8.0:GHC.Prim.Word8#’
                  with actual type ‘ghc-prim-0.8.0:GHC.Prim.Word#’
    • In the first argument of ‘W8#’, namely
        ‘(narrow8Word# (x# `shiftL#` i#))’
      In the expression: W8# (narrow8Word# (x# `shiftL#` i#))
      In an equation for ‘shiftL’:
          shiftL (W8# x#) (I# i#) = W8# (narrow8Word# (x# `shiftL#` i#))
   |
53 | shiftL (W8# x#) (I# i#) = W8# (narrow8Word# (x# `shiftL#` i#))
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Data/CharSet/ByteSet.hs:53:46: error:
    • Couldn't match expected type ‘ghc-prim-0.8.0:GHC.Prim.Word#’
                  with actual type ‘ghc-prim-0.8.0:GHC.Prim.Word8#’
    • In the first argument of ‘shiftL#’, namely ‘x#’
      In the first argument of ‘narrow8Word#’, namely ‘(x# `shiftL#` i#)’
      In the first argument of ‘W8#’, namely
        ‘(narrow8Word# (x# `shiftL#` i#))’
   |
53 | shiftL (W8# x#) (I# i#) = W8# (narrow8Word# (x# `shiftL#` i#))
   |                                              ^^
```

**Comment by RyanGlScott** [comment]
What version of `charset` are you building? `charset-0.3.9` should build with GHC 9.2.1. (See the changelog [here](https://hackage.haskell.org/package/charset-0.3.9/changelog).)

**Comment by expipiplus1** [comment]
ah, must have been an old version! Sorry for the noise

**Comment by Bodigrim** [comment]
As a Hackage trustee I made a revision to prohibit unbuildable configuration:
https://hackage.haskell.org/package/charset-0.3.7.1/revisions/

**Comment by RyanGlScott** [comment]
Thanks, @Bodigrim! Just to be on the safe side, I've applied the same revision to all older versions of `charset` than contain the affected code in `Data.CharSet.ByteSet`. I'm not sure if it's actually possible to construct build plans for all of these versions using GHC 9.2, but better safe than sorry.
